apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
---

StorageClass
Secret
PersistentVolume
PersistentVolumeClaim
Ingress
ClusterRole
ServiceAccount
ClusterRoleBinding
Service
Deployment
