apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-token
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins-admin
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-ssl
  namespace: jenkins
data:
  tls.crt: ""
  tls.key: ""
type: kubernetes.io/tls
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home
  labels:
    app: jenkins
spec:
  storageClassName: ""
  claimRef:
    name: jenkins-home
    namespace: jenkins
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: ""
    server: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: jenkins
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress




---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole




---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding





---
apiVersion: v1
kind: Service




---
apiVersion: apps/v1
kind: Deployment




